я рисунок забыл добавить. теперь добавил
VasilBykov/Arkansus_code pull request #6
Opened 2024-12-18 23:29 UTC by Pavel1586

2024-12-18 23:30 UTC, VasilBykov commented
Исправь ошибку

2024-12-18 23:34 UTC, VasilBykov requested changes
Рисунок не подходит. 1) Надписи на английском 2) рисунок должен быть целостным 
Пример:
![image](https://github.com/user-attachments/assets/b4c2e7e5-d994-4c66-98b7-1e78618d80c1)

2024-12-18 23:37 UTC, Pavel1586 commented
как я это нарисую?

2024-12-19 00:14 UTC, VasilBykov commented
Даник нарисовал примерно такую картинку

2024-12-19 22:35 UTC, closed without merging